### ISSUE TITLE
Issue with publishing packages to PSGallery

### ISSUE THREAD

**Issue by eelkram** [RichieBzzzt/PowerShellGalleryPublisher#21]
Hi @RichieBzzzt,

I've been using your task to publish a few modules to the PowerShell Gallery.  When I made some changes today to one of them I see the task is now failing internally.

I'm using a Hosted VS2017 agent.

Error:
[error]File not found: 'D:\a\_tasks\PublishPackageToPowerShellGallery_183c9b19-ac1d-56d8-b5a9-9ba71ef843af\0.594.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'

Thoughts?

Thanks,
Mark

**Comment by RichieBzzzt** [comment]
Hello! 

Have you got the latest version installed? I had a bug in an earlier version that was messing up finding the psd1 file.

 If you do let me know and I’ll download the task and unpack to double check that the bug is missing from the latest version. 

And if indeed it does have the latest version then it might be a case of uninstalling and reinstalling the task.

**Comment by RichieBzzzt** [comment]
If I get the time I’ll kick off a release that also uses the hosted agents to publish a module of mine. Funnily enough I’m in the process of adding a release that will publish a module across a variety of agents as opposed to just running the pester tests.

**Comment by eelkram** [comment]
Hi @RichieBzzzt, 

I tested out uninstalling and removing the task and re-installing and have the same issue.  The version that got installed was v0.594.0.  

Thanks,
Mark

**Comment by RichieBzzzt** [comment]
Oh dear. Alright cheers, I’ll take a look first thing tomorrow (UK time)

**Comment by RichieBzzzt** [comment]
Ah OK, I think I may have figured out what the problem is. Seems when I upgraded the task to PowerShell3 I neglected to include the VSTSTaskSdk, which needs to be included. I'll do some internal testing and if all good I'll publish the latest version.

**Comment by RichieBzzzt** [comment]
OK I've tested it and I've resolved the issue. I still need to upgrade the task properly, but I'll leave that for now and get a working version published.

**Comment by eelkram** [comment]
Thanks @RichieBzzzt, looking good.  I used it tonight to publish a few updates without issue.
